 #  <-- tasks file can include smaller files if warranted
---
- name: be sure nginx is installed
  apt: pkg=nginx state=installed
  sudo: yes
  tags: nginx

#- name: be sure ntp is configured
#  template: src=ntp.conf.j2 dest=/etc/ntp.conf
#  notify:
#    - restart ntp
#  sudo: yes
#  tags: ntp

- name: be sure nginx is running and enabled
  service: name=nginx state=running enabled=yes
  sudo: yes
  tags: nginx

- name: be sure artifact extracted to correct path
  unarchive: src=../../../web.zip dest=/usr/share/nginx/html/
  sudo: yes
  tags: web-artifact