 #  <-- tasks file can include smaller files if warranted
---
- name: be sure nginx is installed
  apt: pkg=nginx state=installed
  sudo: yes
  tags: nginx

- name: be sure nginx is configured
  copy: src=default dest=/etc/nginx/sites-enabled/default owner=root group=root mode=644 backup=yes
  sudo: yes
  tags: nginx


- name: be sure nginx is running and enabled
  service: name=nginx state=running enabled=yes
  sudo: yes
  tags: nginx

- name: be sure artifact extracted to correct path
  unarchive: src=web.zip dest={{ web_tier_location }}
  sudo: yes
  tags: deploy

# - name: Check out the latest revision of the codebase and notify the proper handlers if there have been updates
#   git: repo=https://github.com/nahknarmi/wli-webtier accept_hostkey=yes
#        dest={{ web_tier_location }}/current
#   sudo: yes
#   notify:
#     # - Symlink the log directory to the shared location
#     # - Install the bundle
#     - Restart nginx
#   tags: deploy  