 #  <-- tasks file can include smaller files if warranted
---
- name: be sure ntp is installed
  apt: pkg=ntp state=installed
  sudo: yes
  tags: ntp

- name: be sure ntp is configured
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  sudo: yes
  notify:
    - restart ntp
  tags: ntp

- name: be sure ntp is running and enabled
  service: name=ntp state=running enabled=yes
  sudo: yes
  tags: ntp

- name: be sure unzip is installed
  apt: pkg=unzip state=present update_cache=yes
  sudo: yes
  tags: unzip
